---
# tasks file for reboot-and-wait

- name: Initialize a server reboot
  command: /usr/bin/systemd-run --on-active={{ reboot_delay }} /usr/bin/systemctl reboot
  become: yes
  become_user: root
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to come back
  wait_for: 
    host: "{{ inventory_hostname }}"
    state: started
    port: "{{ return_port }}"
    delay: "{{ return_delay }}"
    timeout: "{{ return_timeout }}"
    connect_timeout: "{{ return_connect_timeout }}"
  delegate_to: 127.0.0.1
  become: false
