---
# tasks file for reboot-and-wait

- name: Initialize a server reboot
  command: /usr/bin/systemd-run --on-active=5 /usr/bin/systemctl reboot
  become: yes
  become_user: root
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to come back
  local_action: "wait_for host={{ inventory_hostname }} state=started port=22 delay=60 timeout=300 connect_timeout=20"
  become: false
